<?php

return [
    /**
     * Push Notification Settings.
     */
    [
        'key'  => 'mobile_app.push_notifications',
        'name' => 'push_notification::app.settings.title',
        'info' => 'push_notification::app.settings.info',
        'sort' => 11,
    ],
    [
        'key'  => 'mobile_app.push_notifications.general',
        'name' => 'push_notification::app.settings.general.title',
        'info' => 'push_notification::app.settings.general.info',
        'icon' => 'settings/store.svg',
        'sort' => 1,
    ],
    [
        'key'    => 'mobile_app.push_notifications.general.settings',
        'name'   => 'push_notification::app.settings.general.settings.title',
        'info'   => 'push_notification::app.settings.general.settings.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'    => 'enabled',
                'title'   => 'push_notification::app.settings.fields.enabled',
                'info'    => 'push_notification::app.settings.fields.enabled-info',
                'type'    => 'boolean',
                'default' => false,
            ],
            [
                'name'    => 'firebase_credentials_json',
                'title'   => 'push_notification::app.settings.fields.firebase-credentials-json',
                'info'    => 'push_notification::app.settings.fields.firebase-credentials-json-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'firebase_project_id',
                'title'   => 'push_notification::app.settings.fields.firebase-project-id',
                'info'    => 'push_notification::app.settings.fields.firebase-project-id-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'statuses',
                'title'   => 'push_notification::app.settings.fields.statuses',
                'info'    => 'push_notification::app.settings.fields.statuses-info',
                'type'    => 'multiselect',
                'default' => '',
                'depends' => 'enabled:1',
                'options' => [
                    ['title' => 'push_notification::app.settings.order-status.pending', 'value' => 'pending'],
                    ['title' => 'push_notification::app.settings.order-status.pending-payment', 'value' => 'pending_payment'],
                    ['title' => 'push_notification::app.settings.order-status.processing', 'value' => 'processing'],
                    ['title' => 'push_notification::app.settings.order-status.preparing', 'value' => 'preparing'],
                    ['title' => 'push_notification::app.settings.order-status.ready', 'value' => 'ready'],
                    ['title' => 'push_notification::app.settings.order-status.completed', 'value' => 'completed'],
                    ['title' => 'push_notification::app.settings.order-status.canceled', 'value' => 'canceled'],
                    ['title' => 'push_notification::app.settings.order-status.closed', 'value' => 'closed'],
                ],
            ],
        ],
    ],
    [
        'key'    => 'mobile_app.push_notifications.general.messages',
        'name'   => 'push_notification::app.settings.general.messages.title',
        'info'   => 'push_notification::app.settings.general.messages.info',
        'sort'   => 2,
        'fields' => [
            [
                'name'    => 'title_pending',
                'title'   => 'push_notification::app.settings.fields.title-pending',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_pending',
                'title'   => 'push_notification::app.settings.fields.body-pending',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_pending_payment',
                'title'   => 'push_notification::app.settings.fields.title-pending-payment',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_pending_payment',
                'title'   => 'push_notification::app.settings.fields.body-pending-payment',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_processing',
                'title'   => 'push_notification::app.settings.fields.title-processing',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_processing',
                'title'   => 'push_notification::app.settings.fields.body-processing',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_preparing',
                'title'   => 'push_notification::app.settings.fields.title-preparing',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_preparing',
                'title'   => 'push_notification::app.settings.fields.body-preparing',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_ready',
                'title'   => 'push_notification::app.settings.fields.title-ready',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_ready',
                'title'   => 'push_notification::app.settings.fields.body-ready',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_completed',
                'title'   => 'push_notification::app.settings.fields.title-completed',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_completed',
                'title'   => 'push_notification::app.settings.fields.body-completed',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_canceled',
                'title'   => 'push_notification::app.settings.fields.title-canceled',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_canceled',
                'title'   => 'push_notification::app.settings.fields.body-canceled',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
            [
                'name'    => 'title_closed',
                'title'   => 'push_notification::app.settings.fields.title-closed',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'body_closed',
                'title'   => 'push_notification::app.settings.fields.body-closed',
                'info'    => 'push_notification::app.settings.fields.placeholder-info',
                'type'    => 'textarea',
                'default' => '',
            ],
        ],
    ],
];
