version = 5.3.1
archive_dir = /etc/letsencrypt/archive/surprise.softnova.ru
cert = /etc/letsencrypt/live/surprise.softnova.ru/cert.pem
privkey = /etc/letsencrypt/live/surprise.softnova.ru/privkey.pem
chain = /etc/letsencrypt/live/surprise.softnova.ru/chain.pem
fullchain = /etc/letsencrypt/live/surprise.softnova.ru/fullchain.pem
[renewalparams]
account = d58dc98b316c45b8d8cf163060befb56
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
surprise.softnova.ru = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-04-10T09:05:14
