<?php

return [
    /**
     * Mobile App Settings.
     */
    [
        'key'  => 'mobile_app',
        'name' => 'mobile_app::app.settings.title',
        'info' => 'mobile_app::app.settings.info',
        'sort' => 10,
    ],
    [
        'key'  => 'mobile_app.general',
        'name' => 'mobile_app::app.settings.general.title',
        'info' => 'mobile_app::app.settings.general.info',
        'icon' => 'settings/store.svg',
        'sort' => 1,
    ],
    [
        'key'    => 'mobile_app.general.app_info',
        'name'   => 'mobile_app::app.settings.general.app-info.title',
        'info'   => 'mobile_app::app.settings.general.app-info.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'    => 'app_name',
                'title'   => 'mobile_app::app.settings.fields.app-name',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'app_version',
                'title'   => 'mobile_app::app.settings.fields.app-version',
                'type'    => 'text',
                'default' => '1.0.0',
            ],
            [
                'name'    => 'min_app_version',
                'title'   => 'mobile_app::app.settings.fields.min-app-version',
                'type'    => 'text',
                'default' => '1.0.0',
            ],
            [
                'name'    => 'force_update',
                'title'   => 'mobile_app::app.settings.fields.force-update',
                'type'    => 'boolean',
                'default' => false,
            ],
            [
                'name'    => 'maintenance_mode',
                'title'   => 'mobile_app::app.settings.fields.maintenance-mode',
                'type'    => 'boolean',
                'default' => false,
            ],
        ],
    ],
    [
        'key'    => 'mobile_app.general.custom',
        'name'   => 'mobile_app::app.settings.general.custom.title',
        'info'   => 'mobile_app::app.settings.general.custom.info',
        'sort'   => 2,
        'fields' => [
            [
                'name'  => 'custom_data',
                'title' => 'mobile_app::app.settings.fields.custom-data',
                'info'  => 'mobile_app::app.settings.fields.custom-data-info',
                'type'  => 'textarea',
            ],
        ],
    ],
    [
        'key'    => 'mobile_app.general.contact_us',
        'name'   => 'mobile_app::app.settings.general.contact-us.title',
        'info'   => 'mobile_app::app.settings.general.contact-us.info',
        'sort'   => 3,
        'fields' => [
            [
                'name'    => 'contact_telegram',
                'title'   => 'mobile_app::app.settings.fields.contact-telegram',
                'info'    => 'mobile_app::app.settings.fields.contact-telegram-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'contact_whatsapp',
                'title'   => 'mobile_app::app.settings.fields.contact-whatsapp',
                'info'    => 'mobile_app::app.settings.fields.contact-whatsapp-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'contact_email',
                'title'   => 'mobile_app::app.settings.fields.contact-email',
                'info'    => 'mobile_app::app.settings.fields.contact-email-info',
                'type'    => 'text',
                'default' => '',
            ],
            [
                'name'    => 'contact_max',
                'title'   => 'mobile_app::app.settings.fields.contact-max',
                'info'    => 'mobile_app::app.settings.fields.contact-max-info',
                'type'    => 'text',
                'default' => '',
            ],
        ],
    ],
    /**
     * Push Notifications Settings.
     */
    [
        'key'  => 'mobile_app.push_notifications',
        'name' => 'mobile_app::app.settings.push-notifications.title',
        'info' => 'mobile_app::app.settings.push-notifications.info',
        'icon' => 'settings/store.svg',
        'sort' => 2,
    ],
    [
        'key'    => 'mobile_app.push_notifications.settings',
        'name'   => 'mobile_app::app.settings.push-notifications.settings.title',
        'info'   => 'mobile_app::app.settings.push-notifications.settings.info',
        'sort'   => 1,
        'fields' => [
            [
                'name'    => 'enabled',
                'title'   => 'mobile_app::app.settings.fields.push-enabled',
                'info'    => 'mobile_app::app.settings.fields.push-enabled-info',
                'type'    => 'boolean',
                'default' => false,
            ],
            [
                'name'    => 'firebase_credentials_json',
                'title'   => 'mobile_app::app.settings.fields.firebase-credentials-json',
                'info'    => 'mobile_app::app.settings.fields.firebase-credentials-json-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'firebase_project_id',
                'title'   => 'mobile_app::app.settings.fields.firebase-project-id',
                'info'    => 'mobile_app::app.settings.fields.firebase-project-id-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'statuses',
                'title'   => 'mobile_app::app.settings.fields.push-statuses',
                'info'    => 'mobile_app::app.settings.fields.push-statuses-info',
                'type'    => 'multiselect',
                'default' => '',
                'depends' => 'enabled:1',
                'options' => [
                    ['title' => 'mobile_app::app.settings.order-status.pending', 'value' => 'pending'],
                    ['title' => 'mobile_app::app.settings.order-status.pending-payment', 'value' => 'pending_payment'],
                    ['title' => 'mobile_app::app.settings.order-status.processing', 'value' => 'processing'],
                    ['title' => 'mobile_app::app.settings.order-status.preparing', 'value' => 'preparing'],
                    ['title' => 'mobile_app::app.settings.order-status.ready', 'value' => 'ready'],
                    ['title' => 'mobile_app::app.settings.order-status.completed', 'value' => 'completed'],
                    ['title' => 'mobile_app::app.settings.order-status.canceled', 'value' => 'canceled'],
                    ['title' => 'mobile_app::app.settings.order-status.closed', 'value' => 'closed'],
                ],
            ],
        ],
    ],
    [
        'key'    => 'mobile_app.push_notifications.messages',
        'name'   => 'mobile_app::app.settings.push-notifications.messages.title',
        'info'   => 'mobile_app::app.settings.push-notifications.messages.info',
        'sort'   => 2,
        'fields' => [
            [
                'name'    => 'title_pending',
                'title'   => 'mobile_app::app.settings.fields.push-title-pending',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_pending',
                'title'   => 'mobile_app::app.settings.fields.push-body-pending',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_pending_payment',
                'title'   => 'mobile_app::app.settings.fields.push-title-pending-payment',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_pending_payment',
                'title'   => 'mobile_app::app.settings.fields.push-body-pending-payment',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_processing',
                'title'   => 'mobile_app::app.settings.fields.push-title-processing',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_processing',
                'title'   => 'mobile_app::app.settings.fields.push-body-processing',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_preparing',
                'title'   => 'mobile_app::app.settings.fields.push-title-preparing',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_preparing',
                'title'   => 'mobile_app::app.settings.fields.push-body-preparing',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_ready',
                'title'   => 'mobile_app::app.settings.fields.push-title-ready',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_ready',
                'title'   => 'mobile_app::app.settings.fields.push-body-ready',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_completed',
                'title'   => 'mobile_app::app.settings.fields.push-title-completed',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_completed',
                'title'   => 'mobile_app::app.settings.fields.push-body-completed',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_canceled',
                'title'   => 'mobile_app::app.settings.fields.push-title-canceled',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_canceled',
                'title'   => 'mobile_app::app.settings.fields.push-body-canceled',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'title_closed',
                'title'   => 'mobile_app::app.settings.fields.push-title-closed',
                'info'    => 'mobile_app::app.settings.fields.push-info',
                'type'    => 'text',
                'default' => '',
                'depends' => 'enabled:1',
            ],
            [
                'name'    => 'body_closed',
                'title'   => 'mobile_app::app.settings.fields.push-body-closed',
                'info'    => 'mobile_app::app.settings.fields.push-body-info',
                'type'    => 'textarea',
                'default' => '',
                'depends' => 'enabled:1',
            ],
        ],
    ],
];


